### ISSUE TITLE
allow to use underwater mount in "Summons 2"

### ISSUE THREAD

**Issue by Ricstrasz** [sfmict/MountsJournal#40]
I like this addon.
But I dont understand why "Summons 2" is restrict to use underwater mount.

My scenario, I would like to summon my underwater mount when the condition "Player is swimming" met on "Summons 2" button. I have use "Summon 1" with ground+fly+swim mount, and would like to use "Summons 2" with ground+swim mount only, like those tutles.

**Comment by sfmict** [comment]
Hi, You needed a way to summon a non-swimming mount in water, so summon 2 was added for that. I mb reconsider this behavior, but for now this is how it works. You can change some behavior in the rules, gl :)

**Comment by Ricstrasz** [comment]
I have tried change it in rules, but it seems rules cannot overside the global settings.
Can you add an option to disable the global settings? this will make summon 2 button more useful.

**Comment by sfmict** [comment]
Yes, right now you can create a list with only ground mounts and set it in the rules for that behavior.

**Comment by sfmict** [comment]
Hi, I made that you can disable default behavior of the summon 2

**Comment by sfmict** [comment]
You can do this if you create profiles for swimming, land and flying. It's not the alternative mod, it's a summoning rule.
Maybe I should create actions to summon flying, land and water mounts.

**Comment by Ricstrasz** [comment]
I have those, but none of the profile works with the rule to override the alternative mode settings


Ricky
________________________________

**Comment by sfmict** [comment]
I don't understand what do you mean by "override the alternative mode settings"? Alternative mod can be disabled or not.

**Comment by Ricstrasz** [comment]
I meant I can create those profiles, but as long as profile is related to in water or on ground, they won't work, only whatever alternative mode is on or off works.


Ricky
________________________________

**Comment by sfmict** [comment]
If you have a profile with only fly or ground mounts this works

**Comment by Ricstrasz** [comment]
Sorry I have a profile and it doesn't work. That's why I had this request.
No matter what profile and rules, as long as the condition is in water or on ground but can fly, it always take the settings from alternative mode.

How can I send some logs to you?


Ricky
________________________________

**Comment by sfmict** [comment]
You can give me the settings from `wow\_retail_\wtf\Account\AccID\SavedVariables\MountsJounral.lua`

**Comment by sfmict** [comment]
I think I figured out what's going on, I'll add a "Random Mount of Selected Type" action in the next update.

**Comment by Ricstrasz** [comment]
FYI.


Regards,

Ricky
M: 0434 505 777<tel:+61434505777>

**Comment by sfmict** [comment]
Added :)

**Comment by Ricstrasz** [comment]
I think the latest update broke the basic rules.
Now even rule #1 & #2 are not working
Please check my logs attached.
***@***.***

**Comment by sfmict** [comment]
Hm, You use `Random Mount by Rarity` not `Random Mount of Selected Type by Rarity`

**Comment by Ricstrasz** [comment]
I tried both, none of them working at the moment


Ricky
________________________________

**Comment by sfmict** [comment]
I hope this is fixed, check it out :)

**Comment by Ricstrasz** [comment]
Sorry it is still not working.
I have deleted my settings, deleted the addon
re-installed the addon
only change the default rule to "Random Mount of Selected Type by Rarity: Default - Flying", it is still summon "Chauffeur", and always "Chauffeur", not other ground mount, or even flying mount.

I also tried tick "Alternative Mode", it is still summon "Chauffeur".

![Image](https://github.com/user-attachments/assets/e5e157e6-4fca-4cdb-8bd1-9f3968480f2a)

**Comment by sfmict** [comment]
"Chauffeur" is summoned if You don't have any selected mount in the list

**Comment by Ricstrasz** [comment]
I'm 300+ mounts in the list and I'm using everything default with only change the left mouse button rule

**Comment by sfmict** [comment]
Sorry but I can't reproduce your behavior. Mb you should upload the settings  from `wow\_retail_\wtf\Account\AccID\SavedVariables\MountsJounral.lua`

**Comment by Ricstrasz** [comment]
[MountsJournal.zip](https://github.com/user-attachments/files/18718112/MountsJournal.zip)

here's my settings, appreciated, I really dont know what's wrong here.

**Comment by sfmict** [comment]
You don't have selected mounts

![Image](https://github.com/user-attachments/assets/675930f5-866d-4861-b6d4-523a9553b510)

**Comment by Ricstrasz** [comment]
Sorry I think I mis-understood the selected mounts meaning.

I have switched back to "Random Mount by Rarity", but rule 1 "the player is swimming" is aways sommon "Wondrous Wavewishker" for some reason.

Same rule 3 on Left Mouse Button works as expected.

![Image](https://github.com/user-attachments/assets/0d696af1-05c6-44ba-bffe-569029f5545b)

[MountsJournal.zip](https://github.com/user-attachments/files/18718195/MountsJournal.zip)

**Comment by sfmict** [comment]
You are using `Random Mount` not `Random Mount of Selected Type`

**Comment by Ricstrasz** [comment]
Yes, I have switched back to random mounts with profiles, the same profile called "Rare - Flying" worked on mouse button rule but not "when player is swimming rule"


Ricky
________________________________

**Comment by sfmict** [comment]
Mount profiles -> select profile -> profile settings -> Auto add new mounts to selected

**Comment by Ricstrasz** [comment]
now everything works as expected thanks for your patience and explanation. this selected profile had really confused me.

thanks again.

**Comment by sfmict** [comment]
Thanks for the feedback, "Selected" are needed for more control over summoned mounts. Write if you have any ideas :)
